# Site
repository: sudowicked/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Giannis Nikoloulis
title: Informatics Student
email: p18niko@ionio.gr
# email_title: Email (Email title override)
pdf: CV PDF

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  sudowicked
facebook_username: giannis.nik.505
youtube_username: Dzz33kol

# Additional icon links
additional_links:
- title: Steam link
  icon: fab fa-steam
  url: https://steamcommunity.com/profiles/76561198131160944/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi my name is Giannis and I'm currently an undergraduate student at the [Ionian University Department of Informatics](https://di.ionio.gr/en/) <br> My goal careerwise is not defined yet as there are various interesting fields in Information Technology but I plan to make the most out of my academic career
  <br> ![alt text](/images/CORFU.jpg "Corfu City")
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SW
        additional_links:
          - title:  SW
            icon: fab fa-github
            url: https://github.com/sudowicked/sw/tree/2018024/projects/2018024
        quote: >
          My work for the Ionian University Department Of Informatics <br> <mark>SW Project</mark> which consists of 12 deliverables created by me during the <mark> Software Engineering Course </mark> <br> <br> These deliverables were designed to help get a better <br> understanding of how computer programs are designed and maintained
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Ionian University
        sub_title: Department Of Informatics
        caption: October 2018 - Present
        quote: > 
          The purpose of the Department of Informatics is <br> to cultivate and promote the Science of Computing, focusing on the theory and the applications of Informatics in the areas of Humanistic Informatics as well as on the design, development, operation and management of Information Systems
  - title: Languages
    layout: list
    content:
      - layout: right
        description: | # this will include new lines to allow paragraphs
          Greek(Native) <br> English(C2)
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of interests and hobbies are:
      - Working out
      - Music production
      - Gaming
      - Chilling
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
